# Generated by Django 4.2.2 on 2023-11-29 14:30

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
                ('Duration', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('IsActive', models.BooleanField()),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=2)),
                ('Name', models.CharField(max_length=255)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTypes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=255)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfIdentty',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Value', models.CharField(max_length=255)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBatches',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('MeetingURL', models.CharField(max_length=500)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Duration', models.IntegerField()),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('IsActive', models.BooleanField()),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
                ('IsActive', models.BooleanField()),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.userroles')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingStaff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('EmailID', models.CharField(max_length=200)),
                ('IsActive', models.BooleanField()),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('LoginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerQualifications',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CertificateNumber', models.CharField(max_length=255)),
                ('CertifyingAuthority', models.CharField(max_length=255)),
                ('CertificateValidTill', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.languages')),
                ('LevelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.level')),
                ('TrainerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.trainingstaff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBatchAllocation',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('StudentID', models.CharField(max_length=255)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('BatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.trainingbatches')),
                ('TrainerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.trainingstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('TransactionId', models.CharField(max_length=100)),
                ('TransactionStatusId', models.IntegerField()),
                ('IsDiscountApplied', models.BooleanField()),
                ('DiscountedPayment', models.IntegerField(default=0)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.courses')),
                ('PaymentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.paymenttypes')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementStaff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('EmailID', models.CharField(max_length=200)),
                ('IsSuperAdmin', models.BooleanField()),
                ('IsAdmin', models.BooleanField()),
                ('IsActive', models.BooleanField()),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('LoginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='LanguageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.languages'),
        ),
        migrations.AddField(
            model_name='courses',
            name='LevelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.level'),
        ),
    ]
