# Generated by Django 4.2.2 on 2023-12-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
