# Generated by Django 4.2.2 on 2024-01-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]
