# Generated by Django 4.2.2 on 2023-12-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
