# Generated by Django 4.2.2 on 2024-01-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0002_languages_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MobileNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
