# Generated by Django 4.2.2 on 2023-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0002_courses_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='EndtDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
