# Generated by Django 4.2.2 on 2023-12-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0003_alter_user_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Course_metirials',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='Course_status',
            field=models.IntegerField(default=0),
        ),
    ]
