# Generated by Django 4.2.2 on 2024-01-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0003_user_mobilenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='MobileNumber',
            new_name='Mobile_Number',
        ),
    ]
