# Generated by Django 4.2.2 on 2024-01-12 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0004_rename_mobilenumber_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course_metirials',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/Stady_metirials', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='trainingbatches',
            name='EndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainingbatches',
            name='EndTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trainingbatches',
            name='StartDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainingbatches',
            name='StartTime',
            field=models.TimeField(),
        ),
    ]
