# Generated by Django 4.2.2 on 2023-12-15 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0004_courses_course_metirials_courses_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Course_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.courses'),
        ),
    ]
