# Generated by Django 4.2.2 on 2024-01-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0005_alter_courses_course_metirials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
