# Generated by Django 4.2.2 on 2024-01-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0006_user_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
    ]
