# Generated by Django 4.2.2 on 2024-01-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0007_remove_user_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
