# Generated by Django 4.2.2 on 2024-01-18 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0008_user_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.AddField(
            model_name='payments',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='PaymentStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.paymentstatus'),
        ),
    ]
