# Generated by Django 4.2.2 on 2024-01-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0009_paymentstatus_remove_user_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.studentdetails'),
        ),
    ]
