# Generated by Django 4.2.2 on 2024-01-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0010_payments_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='Student',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='PaymentDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.payments'),
        ),
    ]
