# Generated by Django 5.0.1 on 2024-01-19 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0011_remove_payments_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='payments',
            name='TransactionStatusId',
        ),
        migrations.AddField(
            model_name='payments',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='PaymentMethodId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.paymentmethod'),
        ),
    ]
