# Generated by Django 5.0.1 on 2024-01-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0013_payments_studentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='StudentDetails',
        ),
    ]
