# Generated by Django 5.0.1 on 2024-01-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0015_payments_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='StudentDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.studentdetails'),
        ),
    ]
