# Generated by Django 4.2.2 on 2024-01-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0016_alter_payments_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
